# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(393, 346)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.containeerStatus = QtWidgets.QHBoxLayout()
        self.containeerStatus.setSpacing(24)
        self.containeerStatus.setObjectName("containeerStatus")
        self.label_2 = QtWidgets.QLabel(parent=Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.containeerStatus.addWidget(self.label_2)
        self.labelStatus = QtWidgets.QLabel(parent=Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelStatus.sizePolicy().hasHeightForWidth())
        self.labelStatus.setSizePolicy(sizePolicy)
        self.labelStatus.setMinimumSize(QtCore.QSize(40, 0))
        self.labelStatus.setMaximumSize(QtCore.QSize(40, 16777215))
        self.labelStatus.setObjectName("labelStatus")
        self.containeerStatus.addWidget(self.labelStatus)
        self.verticalLayout.addLayout(self.containeerStatus)
        self.icon = QtWidgets.QLabel(parent=Widget)
        self.icon.setObjectName("icon")
        self.verticalLayout.addWidget(self.icon)
        self.labelMovementName = QtWidgets.QLabel(parent=Widget)
        self.labelMovementName.setObjectName("labelMovementName")
        self.verticalLayout.addWidget(self.labelMovementName)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonRecord = QtWidgets.QPushButton(parent=Widget)
        self.buttonRecord.setObjectName("buttonRecord")
        self.horizontalLayout.addWidget(self.buttonRecord)
        self.buttonPlay = QtWidgets.QPushButton(parent=Widget)
        self.buttonPlay.setEnabled(False)
        self.buttonPlay.setObjectName("buttonPlay")
        self.horizontalLayout.addWidget(self.buttonPlay)
        self.counterLoopValue = QtWidgets.QSpinBox(parent=Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.counterLoopValue.sizePolicy().hasHeightForWidth())
        self.counterLoopValue.setSizePolicy(sizePolicy)
        self.counterLoopValue.setMinimumSize(QtCore.QSize(20, 0))
        self.counterLoopValue.setObjectName("counterLoopValue")
        self.horizontalLayout.addWidget(self.counterLoopValue)
        #self.buttonSave = QtWidgets.QPushButton(parent=Widget)
        #self.buttonSave.setEnabled(False)
        #self.buttonSave.setObjectName("buttonSave")
        #self.horizontalLayout.addWidget(self.buttonSave)
        self.verticalLayout.addLayout(self.horizontalLayout)
        #self.cbSaves = QtWidgets.QComboBox(parent=Widget)
        #self.cbSaves.setObjectName("cbSaves")
        #self.verticalLayout.addWidget(self.cbSaves)
        self.containerControll = QtWidgets.QVBoxLayout()
        self.containerControll.setObjectName("containerControll")
        self.verticalLayout.addLayout(self.containerControll)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Remote Mouse Controller"))
        self.label_2.setText(_translate("Widget", "Status: "))
        self.labelStatus.setText(_translate("Widget", "Idle"))
        self.icon.setText(_translate("Widget", "<html><head/><body><p><span style=\" font-weight:700;\">⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣏⡦⠤⣤⠽⠤⡄</span></p><p><span style=\" font-weight:700;\">⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⡤⠤⠣⢈⠇⠀⠁⣠⡿⡄</span></p><p><span style=\" font-weight:700;\">⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡠⠂⠉⠀⠀⠀⠀⠀⢀⡀⠈⠀⠀⠈</span> Automatic Mouse</p><p><span style=\" font-weight:700;\">⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡔⠀⠀⠀⠀⠀⡀⠀⡰⣯⡀</span>⠀⠀⠀⠀ Controller</p><p><span style=\" font-weight:700;\">⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⠁⠀⠀⠀⠀⠀⡹⠂⢽⠎⠁⠀⠀⠀⠀</span></p><p><span style=\" font-weight:700;\">⠀⠀⠀⠀⠀⠀⠀⣀⠠⠄⠃⣴⠀⠀⢀⡠⠊</span>⠀⠀⠀⠀⠀⠀⠀⠀⠀</p><p><span style=\" font-weight:700;\">⠈⠉⠉⠉⠉⠉⠉⠀⠀⠀⠀⠈⠧⣢⠌⣁⠐⠋⠂</span>⠀<br/><br/></p></body></html>"))
        self.labelMovementName.setText(_translate("Widget", "No Movement selected"))
        self.buttonRecord.setText(_translate("Widget", "Record"))
        self.buttonPlay.setText(_translate("Widget", "Play"))
        #self.buttonSave.setText(_translate("Widget", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec())
